### PR TITLE
Issue #142: Excluding test classes to be packaged in implementation jar

### PR DESCRIPTION
**Pull request by ropalka**
https://github.com/eclipse-ee4j/jstl-api/issues/142

### CODE REVIEW

**Comment by ropalka** [comment]
Hello @volosied - I'm Red Hat Inc. employ. Didn't Red Hat signed ECA on behalf of all employees with Eclipse foundation?

**Comment by ropalka** [comment]
For some reason I'm not able to sign ECA via https://accounts.eclipse.org/legal/eca/validation/87194
I updated my profile - specified Red Hat as employer but I still see that ECA in this PR is not valid :(

**Comment by volosied** [comment]
I'm not sure about if Red Hat did. I thought the ECA is to be signed per individual. You may want to reach out that.

I had trouble with the ECA too after I filled out the [form](https://accounts.eclipse.org/user/eca). My email from Github and the  Eclipse account didn't match. Perhaps that's true for you, too?

**Comment by ropalka** [comment]
You are right, my eclipse.org account is not the same as my github.com account. How to workaround that @volosied ?

**Comment by volosied** [comment]
If you update your eclipse email to your github one and redo the ECA approval then you should be good, I believe. 

Once you got the approval, you can change your Eclipse account email back to the original one. (I think that's what I did myself, too)

**Comment by ropalka** [comment]
Thanks for you assistance @volosied it helped.

**Review by volosied — APPROVED** [review]

**Comment by volosied** [comment]
Following up on this 

- Can you update pom.xml to remove these packages from the manifest  (spotted by @pnicolucci) 
https://github.com/eclipse-ee4j/jstl-api/blob/dc8c91bea5f1c28de3b670e3f2a46aeb4e614532/impl/pom.xml#L200-L201 

- Any chance you could get these tests to run during the maven builds?  Since the tests don't use junit, and they need files as arguments, it might be not be straightforward.  I only manually ran them through the command line.

**Comment by volosied** [comment]
@ropalka  Following up if you get chance to make  the pom.xml update I mentioned above.  Thanks!

**Comment by ropalka** [comment]
> @ropalka Following up if you get chance to make the pom.xml update I mentioned above. Thanks!

Fixed @volosied .

**Comment by ropalka** [comment]
What about running the tests automatically I don't have time capacity to have a look at that these days. I'd recommend to create a enhancement issue to address this problem in the future.

**Comment by volosied** [comment]
Not a problem. This looks for for now.  Thank you, @ropalka :) 

We'll enhance the tests at a later date.

**Pull request merged**
