### PR TITLE
attempting to figure out how to build jstl...

### PR DESCRIPTION
**Pull request by kwsutter**
Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

This is a work in progress...  I'm attempting to get this project to build so that we might be able to get the API and Spec in order (and I guess the Impl for this particular project).  TBH, I don't know how this project ever built with some of the changes I have had to make.  In any case, please review and offer commentary so that we can clean this up.  Thanks!

- I commented out all of the gpg executions.  For normal `mvn clean install` type building, most people don't have gpg on their systems (I don't).  And, do we really need to sign the jar files that we're building locally?  This seems to be a function of the jenkins builds, not normal developer builds.  If we are okay with not running gpg signing, then I would propose we remove these completely from the pom files.  I just commented them out to make it easier to see what I was doing during this experiment.

Decided to be a bit more aggressive and I just removed the gpg processing from the pom.xml files.  If this ever required down the road, then it can be added back in.  But, commenting out the gpg plugins just seemed kind of ugly.  Need to make a decision and move on...

- What is the purpose of the dependency-reduced-pom.xml and why is it under source management?  I see that it is generated during the build of the impl, but my guess is that this file is not needed in github (remove) and we should add it to .gitignore.  Please advise.

I figured out that this file is indeed a temporary file which should not be kept under source control.  Here's a [pretty good explanation](https://stackoverflow.com/questions/35154717/is-dependency-reduced-pom-xml-automatically-used-instead-of-pom-xml?rq=1).  So, I think this file should be deleted and added to .gitignore.

-  I added the version of 1.6.0 to the definition of the exec-maven-plugin.  This missing version was producing a warning from the mvn build process, so I provided it to remove the warning.

-  All of the tld files were not properly referenced as input parameters to the tlddoc generator.  I added the required ${project.basedir} references.  Again, I have no idea how this ever worked with normal mvn processing...

I think that covers my changes.  I can now build locally using `mvn clean install`.   I'm new to this project, so my assumptions may be all wrong.  I'm willing to work through the education to get this project cleaned up.  Thanks!

### CODE REVIEW

**Comment by kwsutter** [comment]
@jgallimore, here's the PR that I requested another set of eyes on...  Thanks!

**Comment by kwsutter** [comment]
I just took this PR out of Draft mode.  I updated the opening Description with the current state of the PR.  I just need a review, approval, and merge so that we can make more progress with the API and Spec.  Thanks!

**Comment by jgallimore** [comment]
@kwsutter This looks good to me. I ran into one further issue - I ran a `mvn -DdryRun=true release:prepare` which failed due to the `<project>` tag in the root pom stretching over multiple lines. Maven tried to add the namespace again, and failed. You can pull in this commit to address that: https://github.com/jgallimore/jstl-api/commit/7e87bea98ea25f3e941962512a98943fdf66364d

Looking at the root pom, and comparing to the Jakarta Enterprise Beans project, a lot of stuff in the root pom could be removed. This commit https://github.com/jgallimore/jstl-api/commit/4f6df3235d4918a39e630d51b78ab96e28da76d6 removes a quite a bit from the pom.xml, and doesn't appear to impact what's actually built (based on a side-by-side comparison of everything in the `target` folders).

Hope that helps!

**Comment by kwsutter** [comment]
> @kwsutter This looks good to me. I ran into one further issue - I ran a `mvn -DdryRun=true release:prepare` which failed due to the `<project>` tag in the root pom stretching over multiple lines. Maven tried to add the namespace again, and failed. You can pull in this commit to address that: [jgallimore@7e87bea](https://github.com/jgallimore/jstl-api/commit/7e87bea98ea25f3e941962512a98943fdf66364d)

Thank you!  I  have incorporated this change into this PR.

> Looking at the root pom, and comparing to the Jakarta Enterprise Beans project, a lot of stuff in the root pom could be removed. This commit [jgallimore@4f6df32](https://github.com/jgallimore/jstl-api/commit/4f6df3235d4918a39e630d51b78ab96e28da76d6) removes a quite a bit from the pom.xml, and doesn't appear to impact what's actually built (based on a side-by-side comparison of everything in the `target` folders).

I was hesitant with making this change.  It's a safe change based on the current structure of the poms.  Since none of the other poms (spec, api, or impl) reference this pom as the parent, then these build dependencies make no difference.  If somebody would decide to do a proper parent pom for this project, then these dependencies may apply.  In the end, I decided to go ahead with your cleanup.  Any type of "parent pom" restructuring would need to figure out the proper content anyway.  Thanks!

**Comment by kwsutter** [comment]
Let's not merge this until we figure out what to do with the EE4J_8 branch contents...  It looks like that should mostly be merged into Master before continuing...

**Comment by bshannon** [comment]
> Let's not merge this until we figure out what to do with the EE4J_8 branch contents... It looks like that should mostly be merged into Master before continuing... 

Almost certainly.

Is it past time to audit all the repos for unmerged EE4J_8 branches?

**Comment by kwsutter** [comment]
> Is it past time to audit all the repos for unmerged EE4J_8 branches?

I really think it's just because this Project was neglected.  The other Projects have much more active participation.  I don't think an "audit" is necessary.

**Comment by arjantijms** [comment]
Isn't it time to merge this? ;)

**Comment by arjantijms** [comment]
I'll close this for now. We have figured out how to build JSTL, so we should be okay. Otherwise this PR can always be re-opened.

**Pull request closed without merging**
