### PR TITLE
Merge EE4J_8 branch with Master?

### PR DESCRIPTION
**Pull request by kwsutter**
It looks like all of Jakarta EE 8 was done in this separate EE4J_8 branch and it was never merged into Master.  We should figure out which of these changes should get merged into Master before we entertain more changes like I was proposing in PR #45.  Thanks!

I don't see any big issues with any of these changes.  We should get somebody with more background than me to review these changes and then let's get these changes merged into Master.  And, then I can rebase my  PR #45 on the updated Master.

### CODE REVIEW

**Comment by pnicolucci** [comment]
I agree nothing here looks concerning, I wasn't however involved in these initial changes so I don't have much background on them. It does look like we'll need to resolve the conflicts on this PR before merging as well.

**Comment by kwsutter** [comment]
@pnicolucci, I understand from talking with @m0mus that @senivam will be trying to resolve this PR merge issue.  Supposedly, this will be done within the day (if possible).  Thanks!

**Comment by senivam** [comment]
as soon as the merge of EE4J_8 branch is required in order to proceed with jakartization of JSTL I've created a #47 PR which includes merge of EE4J_8 branch and jakartization of JSTL itself.

**Comment by kwsutter** [comment]
@senivam took care of the intent of this PR via his PR #47.  Closing this PR.  Thanks!

**Pull request closed without merging**
