### PR TITLE
Update README.md to include location of the implementation

### PR DESCRIPTION
**Pull request by pnicolucci**

### CODE REVIEW

**Comment by arjantijms** [comment]
I would emphasis that *a* implementation of Jakarta Tags is available in the WaSP project, and that that specific implementation was previously in this project. There are also implementations from e.g. Tomcat.

**Comment by pnicolucci** [comment]
@arjantijms  happy with the updates? Thanks for the review!

**Comment by arjantijms** [comment]
What about something along the lines of:

"The Jakarta Tags implementation that was previously in this project is now part of the Eclipse WaSP project: https://projects.eclipse.org/projects/ee4j.wasp. 

The first version of Eclipse WaSP that contained the Jakarta Tags implementation that was previously in this project was 3.2.0: https://projects.eclipse.org/projects/ee4j.wasp/releases/3.2.0.

This project now contains only the Jakarta Tags API."

**Comment by pnicolucci** [comment]
@arjantijms if no other suggested changes then I'll merge. Thanks!

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
@pnicolucci lgtm :)

**Pull request merged**
